-- CreateTable
CREATE TABLE "PricingConfig" (
    "id" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "baseLeadCost" DOUBLE PRECISION NOT NULL DEFAULT 500,
    "hazardNonHazardous" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "hazardClass1" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    "hazardClass2" DOUBLE PRECISION NOT NULL DEFAULT 1.8,
    "hazardClass3" DOUBLE PRECISION NOT NULL DEFAULT 1.6,
    "hazardClass4" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
    "hazardClass5" DOUBLE PRECISION NOT NULL DEFAULT 1.7,
    "hazardClass6" DOUBLE PRECISION NOT NULL DEFAULT 1.9,
    "hazardClass7" DOUBLE PRECISION NOT NULL DEFAULT 2.0,
    "hazardClass8" DOUBLE PRECISION NOT NULL DEFAULT 1.6,
    "hazardClass9" DOUBLE PRECISION NOT NULL DEFAULT 1.3,
    "distanceSameState" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "distanceShort" DOUBLE PRECISION NOT NULL DEFAULT 1.3,
    "distanceMedium" DOUBLE PRECISION NOT NULL DEFAULT 1.6,
    "distanceLong" DOUBLE PRECISION NOT NULL DEFAULT 2.0,
    "quantityRanges" JSONB NOT NULL,
    "vehicleTruck" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "vehicleContainer" DOUBLE PRECISION NOT NULL DEFAULT 1.1,
    "vehicleTanker" DOUBLE PRECISION NOT NULL DEFAULT 1.3,
    "vehicleIsoTank" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
    "vehicleFlatbed" DOUBLE PRECISION NOT NULL DEFAULT 1.1,
    "vehicleRefrigerated" DOUBLE PRECISION NOT NULL DEFAULT 1.4,
    "urgencyMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.3,
    "tierPremiumDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0.7,
    "tierStandardDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0.85,
    "tierFreeDiscount" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PricingConfig_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "PricingConfig_isActive_idx" ON "PricingConfig"("isActive");
